### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ThanhPham1987** [The-AI-Summer/Deep-Learning-In-Production#2]
Hi @black0017 @SergiosKar 
When i run this code from the article "Deploy a Deep Learning model as a web application using Flask and Tensorflow". I have a issue:
ModuleNotFoundError: No module named 'tensorflow_examples'
What should i do?
Best regards,
PeterPham

**Comment by Mustapha-AJEGHRIR** [comment]
Hello, I'm not from the team !
Maybe you can take a look at here  : https://stackoverflow.com/questions/50313441/modulenotfounderror-no-module-named-tensorflow-examples

**Comment by SergiosKar** [comment]
I have no idea how I missed this issue. Sorry about that. Yeap as @Mustapha-AJEGHRIR suggested, have a look at SO. In some version of TF, `tensorflow examples` are not pre-downloaded. So you will have to manually install them

```
!pip install -q git+https://github.com/tensorflow/examples.git
```
