### ISSUE TITLE
Dataloader not being used in the model.

### ISSUE THREAD

**Issue by ashfarhangi** [The-AI-Summer/Deep-Learning-In-Production#4]
It seems like the data loader is not being used in the model.py. Specificially, the preprocess_train and preprecess_data have been defined again in the model.py. I would appreciate little clarification

https://github.com/The-AI-Summer/Deep-Learning-In-Production/blob/master/10.%20How%20to%20use%20Docker%20containers%20and%20Docker%20Compose%20for%20Deep%20Learning%20applications/dataloader/dataloader.py#L11

**Comment by SergiosKar** [comment]
The `DataLoader` class is called in the `unet.py`. Check it out here: https://github.com/The-AI-Summer/Deep-Learning-In-Production/blob/master/10.%20How%20to%20use%20Docker%20containers%20and%20Docker%20Compose%20for%20Deep%20Learning%20applications/model/unet.py#L47

**Comment by SergiosKar** [comment]
Will close this. Feel free to reopen if you have any issues
